/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Yelson
 */
public class WindowPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form windowPrincipal
     */
    public WindowPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPlaylist = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnHelp = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        cmbMedia = new javax.swing.JComboBox();
        lblService = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnList = new javax.swing.JButton();
        lblService1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/images/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 50));

        btnPlaylist.setBackground(new java.awt.Color(242, 244, 247));
        btnPlaylist.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        btnPlaylist.setForeground(new java.awt.Color(17, 31, 77));
        btnPlaylist.setText("Mi Lista");
        btnPlaylist.setBorder(null);
        btnPlaylist.setBorderPainted(false);
        btnPlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 80, 20));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 31, 77));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("|");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 20, 20));

        jPanel1.setBackground(new java.awt.Color(242, 244, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/images/help.png"))); // NOI18N
        btnHelp.setToolTipText("Centro de ayuda");
        btnHelp.setBorder(null);
        btnHelp.setBorderPainted(false);
        btnHelp.setContentAreaFilled(false);
        btnHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        jPanel1.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 50, 50));
        btnHelp.getAccessibleContext().setAccessibleDescription("");

        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/images/config.png"))); // NOI18N
        btnConfig.setToolTipText("Configuración de Usuario. Ajusta los datos de pago, cuenta, información...");
        btnConfig.setBorder(null);
        btnConfig.setBorderPainted(false);
        btnConfig.setContentAreaFilled(false);
        btnConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 50, 50));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/images/exit.png"))); // NOI18N
        btnExit.setToolTipText("Cerrar Sesión");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 50, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setBackground(new java.awt.Color(17, 31, 77));
        btnAdd.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Agregar a Mi Lista");
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, 30));

        btnPlay.setBackground(new java.awt.Color(17, 31, 77));
        btnPlay.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("Reproducir");
        jPanel2.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, 30));

        cmbMedia.setForeground(new java.awt.Color(17, 31, 77));
        jPanel2.add(cmbMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 370, 340, 30));

        lblService.setFont(new java.awt.Font("Corbel", 1, 26)); // NOI18N
        lblService.setForeground(new java.awt.Color(17, 31, 77));
        lblService.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblService.setText("MI SERVICIO");
        jPanel2.add(lblService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 740, -1));

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        txtArea.setForeground(new java.awt.Color(17, 31, 77));
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 630, 270));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 740, 420));

        btnList.setBackground(new java.awt.Color(242, 244, 247));
        btnList.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        btnList.setForeground(new java.awt.Color(17, 31, 77));
        btnList.setText("Contenido");
        btnList.setBorder(null);
        btnList.setBorderPainted(false);
        btnList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnList, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 110, 20));

        lblService1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblService1.setForeground(new java.awt.Color(102, 102, 102));
        lblService1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblService1.setText("Reproduciendo:");
        jPanel1.add(lblService1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 740, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnConfig;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnHelp;
    public javax.swing.JButton btnList;
    public javax.swing.JButton btnPlay;
    public javax.swing.JButton btnPlaylist;
    public javax.swing.JComboBox cmbMedia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblService;
    public javax.swing.JLabel lblService1;
    public javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
